# Generated by Django 4.0.6 on 2022-07-27 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('prjTitle', models.CharField(max_length=250, verbose_name='ProjectTitle')),
                ('prjSubTitle', models.CharField(max_length=250, verbose_name='ProjectSubTitle')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ProjectMasters',
                'ordering': ['prjTitle'],
                'unique_together': {('prjTitle',)},
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberFormat',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='STANDARD', max_length=50, verbose_name='Category')),
                ('subCategory', models.CharField(default='STANDARD', max_length=50, verbose_name='SubCategory')),
                ('numberPrefix', models.CharField(max_length=50, verbose_name='Number Prefix')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('prjId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.projectmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DocumentNumberFormats',
                'unique_together': {('prjId', 'category', 'subCategory', 'numberPrefix')},
            },
        ),
    ]
